### ISSUE TITLE
Ordering output from joined tables

### ISSUE THREAD

**Issue by ialarmedalien** [damil/DBIx-DataModel#16]
Being able to pull data from related tables is very handy, but is there a way to add an `ORDER BY` clause without using `$row->expand()`, or have a default `ORDER_BY` clause as part of the association?

For example, I have an object with 20+ different compositions/associations to fetch; it would be very handy to set the order that i want each association fetched in as part of the data model.

(This is probably going beyond what DBIx::DataModel is meant for, but I was just wondering if it was possible without specifying it using `$row->expand( 'association', ( -order_by => 'whatever' ) )`.)

**Comment by damil** [comment]
Hi,
At the moment there is no way to define a default ORDER_BY clause in an association. Adding such a feature would not be very difficult, but I doubt that this would be a good idea : how should it behave when joining several associations, i.e. `$schema->join(qw/Table1 assoc1 assoc2 .../)->select(...) `?

For achieving what you want, I would suggest to add supplementary methods in your table classes.
See https://metacpan.org/pod/release/DAMI/DBIx-DataModel-2.46/lib/DBIx/DataModel/Doc/Cookbook.pod#Add-custom-methods-into-a-generated-table-class . Such methods could be more or less like this : 

`sub ordered_assoc1 { my $self = shift; return $self->assoc1(-order_by => 'foo', @_) }`

so the clause `-order_by => 'foo' `is set by default but can be overridden by clauses passed as arguments through @_.

Hope this helps.

Thanks for using DBIx::Datamodel, Laurent d.
