### ISSUE TITLE
Data::Dump chokes on DBIDM Output

### ISSUE THREAD

**Issue by rjattrill** [damil/DBIx-DataModel#6]
When using Data::Dump https://metacpan.org/module/Data::Dump, dump on a DBIDM blessed hash will crash if the hash is a result of a join.

The offending string will look something like this:
activity|a<=>process|p<=>domain|d=
as part of 
'My::Schema::AutoJoin::Task|t<=>activity|a<=>process|p<=>domain|d'

This is probably a bug on Data::Dump rather than DBIDM, but I putting here for tracking until I can generate a simple test case to log against Data::Dump

**Comment by damil** [comment]
The Data::Dump issue is said to be closed (even if still declared as open in github).
So I close the present issue
